universe   = vanilla
executable = /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/run_cutflow.sh
getenv     = True

request_cpus   = 1
request_memory = 2GB
request_disk   = 1GB
notification   = Never
should_transfer_files = NO

log    = /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/condor_logs/cutflow_$(WR)_$(N).log
output = /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/condor_logs/cutflow_$(WR)_$(N).out
error  = /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/condor_logs/cutflow_$(WR)_$(N).err

arguments = 2000 100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=2000
N=100
queue

arguments = 2000 200 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=2000
N=200
queue

arguments = 2000 300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=2000
N=300
queue

arguments = 2000 500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=2000
N=500
queue

arguments = 2000 700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=2000
N=700
queue

arguments = 2000 900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=2000
N=900
queue

arguments = 2000 1100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=2000
N=1100
queue

arguments = 2000 1300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=2000
N=1300
queue

arguments = 2000 1500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=2000
N=1500
queue

arguments = 2000 1700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=2000
N=1700
queue

arguments = 2000 1900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=2000
N=1900
queue

arguments = 4000 100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=100
queue

arguments = 4000 300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=300
queue

arguments = 4000 500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=500
queue

arguments = 4000 700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=700
queue

arguments = 4000 900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=900
queue

arguments = 4000 1100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=1100
queue

arguments = 4000 1300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=1300
queue

arguments = 4000 1500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=1500
queue

arguments = 4000 1700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=1700
queue

arguments = 4000 1900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=1900
queue

arguments = 4000 2100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=2100
queue

arguments = 4000 2300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=2300
queue

arguments = 4000 2500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=2500
queue

arguments = 4000 2700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=2700
queue

arguments = 4000 2900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=2900
queue

arguments = 4000 3100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=3100
queue

arguments = 4000 3300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=3300
queue

arguments = 4000 3500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=3500
queue

arguments = 4000 3700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=3700
queue

arguments = 4000 3900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=4000
N=3900
queue

arguments = 6000 100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=100
queue

arguments = 6000 300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=300
queue

arguments = 6000 500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=500
queue

arguments = 6000 700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=700
queue

arguments = 6000 900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=900
queue

arguments = 6000 1100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=1100
queue

arguments = 6000 1300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=1300
queue

arguments = 6000 1500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=1500
queue

arguments = 6000 1700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=1700
queue

arguments = 6000 1900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=1900
queue

arguments = 6000 2100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=2100
queue

arguments = 6000 2300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=2300
queue

arguments = 6000 2500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=2500
queue

arguments = 6000 2700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=2700
queue

arguments = 6000 2900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=2900
queue

arguments = 6000 3100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=3100
queue

arguments = 6000 3300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=3300
queue

arguments = 6000 3500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=3500
queue

arguments = 6000 3700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=3700
queue

arguments = 6000 3900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=3900
queue

arguments = 6000 4100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=4100
queue

arguments = 6000 4300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=4300
queue

arguments = 6000 4500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=4500
queue

arguments = 6000 4700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=4700
queue

arguments = 6000 4900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=4900
queue

arguments = 6000 5100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=5100
queue

arguments = 6000 5300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=5300
queue

arguments = 6000 5500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=5500
queue

arguments = 6000 5700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=5700
queue

arguments = 6000 5900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=6000
N=5900
queue

arguments = 8000 100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=100
queue

arguments = 8000 300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=300
queue

arguments = 8000 500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=500
queue

arguments = 8000 700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=700
queue

arguments = 8000 900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=900
queue

arguments = 8000 1100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=1100
queue

arguments = 8000 1300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=1300
queue

arguments = 8000 1500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=1500
queue

arguments = 8000 1700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=1700
queue

arguments = 8000 1900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=1900
queue

arguments = 8000 2100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=2100
queue

arguments = 8000 2300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=2300
queue

arguments = 8000 2500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=2500
queue

arguments = 8000 2700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=2700
queue

arguments = 8000 2900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=2900
queue

arguments = 8000 3100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=3100
queue

arguments = 8000 3300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=3300
queue

arguments = 8000 3500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=3500
queue

arguments = 8000 3700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=3700
queue

arguments = 8000 3900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=3900
queue

arguments = 8000 4100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=4100
queue

arguments = 8000 4300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=4300
queue

arguments = 8000 4500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=4500
queue

arguments = 8000 4700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=4700
queue

arguments = 8000 4900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=4900
queue

arguments = 8000 5100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=5100
queue

arguments = 8000 5300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=5300
queue

arguments = 8000 5500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=5500
queue

arguments = 8000 5700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=5700
queue

arguments = 8000 5900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=5900
queue

arguments = 8000 6100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=6100
queue

arguments = 8000 6300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=6300
queue

arguments = 8000 6500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=6500
queue

arguments = 8000 6700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=6700
queue

arguments = 8000 6900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=6900
queue

arguments = 8000 7100 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=7100
queue

arguments = 8000 7300 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=7300
queue

arguments = 8000 7500 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=7500
queue

arguments = 8000 7700 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=7700
queue

arguments = 8000 7900 /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/singnal_sample/cutflow/cutflow_output
WR=8000
N=7900
queue

