
#python /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/reproduce/syst_plotter/integrated/plotter_file/year_sep/EE.py --hist "Obj_PU_Corr_DYCR_Resolved_EE_SS_mlljj" --ymin 1 --ymax 1e4 --output ResolveDYEE_SS_mlljj --xmin 800 --xmax 4000 --xlabel "Same sign m(lljj) (GeV)" --rebin 20 --rmin 0 --rmax 2.0
#python /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/reproduce/syst_plotter/integrated/plotter_file/year_sep/MM.py --hist "Obj_PU_Corr_DYCR_Resolved_MM_SS_mlljj" --ymin 1 --ymax 1e4 --output ResolveDYMM_SS_mlljj --xmin 800 --xmax 4000 --xlabel "Same sign m(lljj) (GeV)" --rebin 20 --rmin 0 --rmax 2.0

#python /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/reproduce/syst_plotter/integrated/plotter_file/year_sep/EE.py --hist "Obj_PU_Corr_DYCR_Resolved_EE_OS_mlljj" --ymin 1 --ymax 1e6 --output ResolveDYEE_OS_mlljj --xmin 800 --xmax 4000 --xlabel "Other sign m(lljj) (GeV)" --rebin 20 --rmin 0 --rmax 2.0
#python /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/reproduce/syst_plotter/integrated/plotter_file/year_sep/MM.py --hist "Obj_PU_Corr_DYCR_Resolved_MM_OS_mlljj" --ymin 1 --ymax 1e6 --output ResolveDYMM_OS_mlljj --xmin 800 --xmax 4000 --xlabel "Other sign m(lljj) (GeV)" --rebin 20 --rmin 0 --rmax 2.0

#python /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/reproduce/syst_plotter/integrated/charge_inclusive_year_combined/resolve/DY/EE.py --hist "DYCR_Resolved_EE_mlljj" --ymin 1 --ymax 1e6 --output ResolveDYEE_mlljj --xmin 800 --xmax 8000 --xlabel "m(lljj) (GeV)" --bins "800,1000,1200,1400,1600,2000,2400,2800,3200,8000" --rmin 0 --rmax 2.0
#python /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/reproduce/syst_plotter/integrated/charge_inclusive_year_combined/resolve/DY/MM.py --hist "DYCR_Resolved_MM_mlljj" --ymin 1 --ymax 1e6 --output ResolveDYMM_mlljj --xmin 800 --xmax 8000 --xlabel "m(lljj) (GeV)" --bins "800,1000,1200,1400,1600,2000,2400,2800,3200,8000" --rmin 0 --rmax 2.0
python /data6/Users/achihwan/SKNanoAnalyzer-v13/plots/HNWR/reproduce/syst_plotter/integrated/charge_inclusive_year_combined/resolve/DY/MM.py --hist "DYCR_Resolved_MM_subleading_lep_pt" --ymin 1 --ymax 1e6 --output ResolveDYMM_subleading_lep_pt --xmin 0 --xmax 400 --xlabel "Subleading Lepton p_{T} (GeV)" --rebin 10 --rmin 0 --rmax 2.0